#define TOU_DEFAULT_MSS 
#define TOU_DEFAULT_RECVWINDOW_SIZE 
#define TOU_DEFAULT_SENDWINDOW_SIZE 
#define TOU_DEFAULT_RECV_WORKBUFFER_SIZE 
#define TOU_DEFAULT_RECV_INBUFFER_SIZE 
#define TOU_DEFAULT_SEND_WORKBUFFER_SIZE 
#define TOU_DEFAULT_SEND_OUTBUFFER_SIZE 
#define TOU_DEFAULT_RECV_CTRLBUFFER_SIZE 
#define TOU_DEFAULT_ACK_TIMEOUT_MS 
#define TOU_DEFAULT_FAST_RETRANSMIT_ACK_COUNT 
#define TOU_DEFAULT_RETRANSMIT_METHOD(conn, expired_pkt, dropped_id, ack_stack_count) 