#ifndef TOU_CONSTS_H
#define TOU_CONSTS_H

// #define TOU_DEBUG_ON

#define TOU_DEFAULT_MSS (1500) // max payload size
#define TOU_DEFAULT_RECVWINDOW_SIZE (10)
#define TOU_DEFAULT_SENDWINDOW_SIZE (50)
#define TOU_DEFAULT_RECV_WORKBUFFER_SIZE (TOU_DEFAULT_MSS * 3)
#define TOU_DEFAULT_RECV_INBUFFER_SIZE (TOU_DEFAULT_MSS * 3)
#define TOU_DEFAULT_SEND_WORKBUFFER_SIZE (TOU_DEFAULT_MSS * 3)
#define TOU_DEFAULT_SEND_OUTBUFFER_SIZE (TOU_DEFAULT_MSS * TOU_DEFAULT_SENDWINDOW_SIZE)
#define TOU_DEFAULT_RECV_CTRLBUFFER_SIZE ((TOU_LEN_PKT_ACK + sizeof(ack_id_t) * TOU_PKT_ACK_MAX_ACK_COUNT) * 5)
#define TOU_DEFAULT_ACK_TIMEOUT_MS (5)

#endif